#!/bin/bash
# Usage: sbatch slurm-serial-job-script
# Prepared By: Kai Xi,  Oct 2014
#              help@massive.org.au

# NOTE: To activate a SLURM option, remove the whitespace between the '#' and 'SBATCH'

# To give your job a name, replace "MyJob" with an appropriate name
#SBATCH --job-name=PON


# To set a project account for credit charging, 
#SBATCH --account=ha75


# Request CPU resource for a serial job
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=12

# Memory usage (MB)
#SBATCH --mem-per-cpu=4000

# Set your minimum acceptable walltime, format: day-hours:minutes:seconds
#SBATCH --time=1-0:00:00


# To receive an email when job completes or fails
#SBATCH --mail-user=nick.wong@monash.edu
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=BEGIN

#SBATCH --array=1-7

# Set the file for output (stdout)
# SBATCH --output=/home/nwong/vh83_scratch/2018-03-27-wgbs-rerun/logs_slurm/bismark-%j-%A-%a.out

# Set the file for error log (stderr)
# SBATCH --error=/home/nwong/vh83_scratch/2018-03-27-wgbs-rerun/logs_slurm/bismark-%j-%A-%a.err


# Use reserved node to run job when a node reservation is made for you already
# SBATCH --reservation=reservation_name

# SBATCH --partition=comp

# SBATCH --dependency=afterok:10567760
# SBATCH --reservation=highmem

# Command to run a serial job
module load gatk/4.1.2.0 
module load picard/2.9.2

REF="/home/nwong/ha75_scratch/nick/refFiles/hg38/bwa_0.7.17-gcc5/hg38_ref_noAlt.fa"
EXOME="/home/nwong/ha75_scratch/nick/refFiles/hg38/agilentClinicalResearchExomeV2/S30409818_Covered.bed"
DBSNP="/home/nwong/ha75_scratch/nick/refFiles/hg38/Homo_sapiens_assembly38.dbsnp138.vcf"
COSMIC="/home/nwong/ha75_scratch/nick/refFiles/hg38/CosmicCodingMuts_hg38_v89.vcf"

R1=`find . -name "*.bam" | awk -v line=$SLURM_ARRAY_TASK_ID '{if (NR == line) print $0}'`
R2=`echo $R1 | sed 's:R1:R3:g'`
R3=`echo $R1 | sed 's:bamfiles_mDups/::g' | sed 's:_mDups.bam::g'`
  
gatk Mutect2 \
     -R ${REF} \
     -I ${R1} \
     --max-mnp-distance 0 \
     -O ${R3}.vcf.gz

