#!/bin/bash
# Usage: sbatch slurm-serial-job-script
# Prepared By: Kai Xi,  Oct 2014
#              help@massive.org.au

# NOTE: To activate a SLURM option, remove the whitespace between the '#' and 'SBATCH'

# To give your job a name, replace "MyJob" with an appropriate name
#SBATCH --job-name=QCTrim


# To set a project account for credit charging, 
#SBATCH --account=ha75


# Request CPU resource for a serial job
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4

# Memory usage (MB)
#SBATCH --mem-per-cpu=4000

# Set your minimum acceptable walltime, format: day-hours:minutes:seconds
#SBATCH --time=1-0:00:00


# To receive an email when job completes or fails
#SBATCH --mail-user=nick.wong@monash.edu
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=BEGIN

#SBATCH --array=1-24

# Set the file for output (stdout)
# SBATCH --output=/home/nwong/vh83_scratch/2018-03-27-wgbs-rerun/logs_slurm/bismark-%j-%A-%a.out

# Set the file for error log (stderr)
# SBATCH --error=/home/nwong/vh83_scratch/2018-03-27-wgbs-rerun/logs_slurm/bismark-%j-%A-%a.err


# Use reserved node to run job when a node reservation is made for you already
# SBATCH --reservation=reservation_name

# SBATCH --partition=comp

# SBATCH --dependency=afterok:10565069
# SBATCH --reservation=highmem

# Command to run a serial job
module load gatk/4.1.2.0 
module load picard/2.9.2
module load R/3.6.0-mkl

REF="/home/nwong/ha75_scratch/nick/refFiles/hg38/bwa_0.7.17-gcc5/hg38_ref_noAlt.fa"
EXOME="/home/nwong/ha75_scratch/nick/refFiles/hg38/agilentClinicalResearchExomeV2/S30409818_Covered.interval"
BAIT="/home/nwong/ha75_scratch/nick/refFiles/hg38/agilentClinicalResearchExomeV2/S30409818_Padded.interval"

R1=`find bamfilesTrimmed -name "*.bam" | awk -v line=$SLURM_ARRAY_TASK_ID '{if (NR == line) print $0}'`
R2=`echo $R1 | sed 's:R1:R3:g'`
R3=`echo $R1 | sed 's:bamfilesTrimmed/::g' | sed 's:.bam::g'`
  
picard CollectAlignmentSummaryMetrics \
  I=${R1} \
  O=QC_Trimmed/${R3}_metrics.txt \
  R=${REF}
  
picard CollectHsMetrics \
  I=${R1} \
  O=QC_Trimmed/${R3}_hs_metrics.txt \
  R=${REF} \
  BAIT_INTERVALS=${BAIT} \
  TARGET_INTERVALS=${EXOME} 

picard CollectInsertSizeMetrics \
  I=${R1} \
  O=QC_Trimmed/${R3}_insert_size_metrics.txt \
  H=QC_Trimmed/${R3}_histogram.pdf \
  M=0.5

picard CollectMultipleMetrics \
  I=${R1} \
  O=QC_Trimmed/${R3}_multi_metrics.txt \
  R=${REF}


