#!/bin/bash
ml load freebayes 

for i in `ls sam/*.bam`
do
j=`echo $i | sed 's:_markedDups.bam::g' | sed 's:sam/::g'`

freebayes --fasta-reference refFiles/GRCm38.fa ${i} > vcf/${j}.vcf
done
mail -s "Freebayes done" nick.wong@monash.edu <<< 'Freebayes Done'
