#!/bin/bash
# Usage: sbatch slurm-serial-job-script
# Prepared By: Kai Xi,  Oct 2014
#              help@massive.org.au

# NOTE: To activate a SLURM option, remove the whitespace between the '#' and 'SBATCH'

# To give your job a name, replace "MyJob" with an appropriate name
#SBATCH --job-name=biscuitAlign


# To set a project account for credit charging, 
#SBATCH --account=bd17


# Request CPU resource for a serial job
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24

# Memory usage (MB)
#SBATCH --mem-per-cpu=4000

# Set your minimum acceptable walltime, format: day-hours:minutes:seconds
#SBATCH --time=3-0:00:00


# To receive an email when job completes or fails
#SBATCH --mail-user=nick.wong@monash.edu
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=BEGIN

#For arrays set the number of array
#SBATCH --array=1-50

# Set the file for output (stdout)
# SBATCH --output=/home/nwong/bd17_scratch/nickwong/wgbs/logs_slurm/biscuit-%j-%A-%a.out

# Set the file for error log (stderr)
# SBATCH --error=/home/nwong/bd17_scratch/nick.wong/wgbs/logs_slurm/biscuit-%j-%A-%a.err


# Use reserved node to run job when a node reservation is made for you already
# SBATCH --reservation=reservation_name

#Set partition if necessary
#SBATCH --partition=comp

#Run after a job
# SBATCH --dependency=afterok:7651852

# Command to run a serial job
module load biscuit/0.3.8.20180515 
module load samtools

R1=`find trimmedFastq -name "*1.fastq" | awk -v line=$SLURM_ARRAY_TASK_ID '{if (NR == line) print $0}'`
R2=`echo $R1 | sed 's:1.fastq:2.fastq:g'`
R3=`echo $R1 | sed 's:trimmedFastq/::g' | sed 's:_-trimmed-pair1.fastq::g'`

biscuit align -t 24 /home/nwong/ha66_scratch/mbp/2018-06-24-methylmagic/referenceFiles/hg38/genome.fa  \
   ${R1} \
   ${R2} > biscuit/${R3}_biscuit.sam 


