#!/bin/bash
# Usage: sbatch slurm-serial-job-script
# Author Nick Wong, Monash Bioinformatics Platform
#     nick.wong@monash.edu

# NOTE: To activate a SLURM option, remove the whitespace between the '#' and 'SBATCH'

# To give your job a name, replace "MyJob" with an appropriate name
#SBATCH --job-name=mixcr


# To set a project account for credit charging, 
#SBATCH --account=df22


# Request CPU resource for a serial job
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4


#SBATCH --profile=task

# Memory usage (MB)
#SBATCH --mem-per-cpu=4000

# Set your minimum acceptable walltime, format: day-hours:minutes:seconds
#SBATCH --time=0-4:00:00


# To receive an email when job completes or fails
#SBATCH --mail-user=nick.wong@monash.edu
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

#SBATCH --partition=genomics

#SBATCH --qos=genomics

# Command to run a serial job need to add binding paths
module load singularity
singularity exec /scratch/rc78/angela.pizzola/mixcr_latest.sif \
mixcr analyze shotgun \
        --species hs \
        --starting-material rna \
        --only-productive \
        OPC_002_RNA_HWGKYDSX2_CTCGACTT_L004_R1.fastq.gz OPC_002_RNA_HWGKYDSX2_CTCGACTT_L004_R2.fastq.gz  \
        OPC_002_RNA