#!/bin/bash
# Usage: sbatch slurm-serial-job-script
# Author Nick Wong, Monash Bioinformatics Platform
#     nick.wong@monash.edu

# NOTE: To activate a SLURM option, remove the whitespace between the '#' and 'SBATCH'

# To give your job a name, replace "MyJob" with an appropriate name
#SBATCH --job-name=sequenza


# To set a project account for credit charging, 
#SBATCH --account=ls25


# Request CPU resource for a serial job
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --profile=task

# Memory usage (MB)
#SBATCH --mem-per-cpu=4000

# Set your minimum acceptable walltime, format: day-hours:minutes:seconds
#SBATCH --time=0-4:00:00


# To receive an email when job completes or fails
#SBATCH --mail-user=nick.wong@monash.edu
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

#SBATCH --partition=genomics

#SBATCH --qos=genomics

# Command to run a serial job
conda activate py38
sequenza-utils bam2seqz \
  -n OPC_002_PBMC_HWGKYDSX2_ACACGACC_L004.sorted.bam \
  -t OPC_002_Tumour_HWGKYDSX2_GCTCGGTA_L004.sorted.bam \
  --fasta /scratch/tn26/refFiles/hg38/bwa_0.7.17-gcc5/hg38_ref_noAlt.fa \
  -gc /scratch/tn26/refFiles/hg38/bwa_0.7.17-gcc5/hg38_ref_noAlt.gc50Base.wig.gz \
  -o OPC_002.out.seqz.gz
