#!/bin/bash
# Usage: sbatch slurm-serial-job-script
# Author Nick Wong, Monash Bioinformatics Platform
#     nick.wong@monash.edu

# NOTE: To activate a SLURM option, remove the whitespace between the '#' and 'SBATCH'

# To give your job a name, replace "MyJob" with an appropriate name
#SBATCH --job-name=tso500


# To set a project account for credit charging, 
#SBATCH --account=mv50


# Request CPU resource for a serial job
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --profile=task

# Memory usage (MB)
#SBATCH --mem-per-cpu=4000

# Set your minimum acceptable walltime, format: day-hours:minutes:seconds
#SBATCH --time=7-0:00:00


# To receive an email when job completes or fails
#SBATCH --mail-user=nick.wong@monash.edu
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

#SBATCH --partition=comp

# Command to run a serial job
module load singularity/3.1.0

export PATH=${PATH}:/usr/local/src/TSO/1.3.1

export TSO=/usr/local/src/TSO/1.3.1
export RESOURCE=/usr/local/src/TSO/1.3.1/resources
#ln -s ${TSO}/TruSight_Oncology_500.img .

export OUTPUT=output
export SINGULARITY_BINDPATH=/scratch/mv50

#singularity run -w ${TSO}/TruSight_Oncology_500.img

${TSO}/TruSight_Oncology_500.sh \
  --engine singularity \
  --resourcesFolder ${RESOURCE} \
  --runFolder 190205_NS500702_0557_AH27C5BGX7 \
  --analysisFolder $OUTPUT 
